name: Release (Windows)

on:
  push:
    tags:
      - 'v*'  # triggers when you push a tag like v0.1.0-alpha.1

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bootstrap requirements
        run: python -m pip install -r scripts/requirements.txt

      - name: Bootstrap build (fetch Qt, configure, build)
        run: python scripts/bootstrap.py --ci

      - name: Install NSIS (for CPack)
        run: choco install nsis -y

      - name: Package with CPack (NSIS .exe)
        run: |
          cmake --build build --config Release
          cmake --install build --config Release --prefix dist
          cd build
          cpack -G NSIS

      - name: Upload installer to the tagged release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.exe
          tag: ${{ github.ref }}
          overwrite: true
